---
title: "eeg_eye_statistical_analysis_with_categorical_data"
---
```{r Initialization}

# Clear all
rm(list=ls())

library(yaml)
library(ggplot2)
library(feather)
library(lme4)
library(simr)
library(here)
library(sjPlot)
library(writexl)
library(ggpubr)
library(sjmisc)


# Read the configuration file
config <- yaml.load_file("../../config.yml")

eeg_eye_r_dataset_path <- here(config$eeg_eye_r_dataset_path)
df <- read.csv(eeg_eye_r_dataset_path)
df <- na.omit(df)
```


```{r Analysis of target and engage option}
# Select only static red team
df_pre_option <- subset(df, df$option_type=='pre_option')
df_static <- subset(df_pre_option, df_pre_option$complexity_type=='S002')

# Select reference level and comparison level
comparions_option <- 'engage_option'
reference_option <- 'caution_option'
df_static <-  subset(df_static, df_static$option==reference_option| df_static$option == comparions_option)

# Convert the character to numeric 
df_static['response'] <- df_static$cog_state
df_static$response[df_static$option==reference_option] <- 0
df_static$response[df_static$option==comparions_option] <- 1

# Fit the mixed effect model
model <- lmer(response ~ prob_high_eng + prob_ave_workload + pupil_size + n_saccades + scan_path_length + n_fixations + (1 |mot),data = df_static)
summary(model)
tab_model(model)
```



```{r Analysis of target and engage option}
# Set the factors 
# df$option <- as.factor(df$option)
# df$option_type <- as.factor(df$option_type)
# df$option <- as.numeric(df$option)

# Select only target and attack option
df_pre_option <- subset(df, df$option_type=='pre_option')
df_static <- subset(df_pre_option, df$complexity_type=='S002')
# df_engage <-  subset(df_static, df_static$option_type=='caution_option' | df_static$option_type == 'target_option')
df_engage <- df_static
df_engage <- na.omit(df_engage)

df_engage$option <- relevel(df_engage$option, "caution_option")
response <-  df_engage$prob_high_eng

# Fit the mixed effect model
model <- glmer(response ~ option +  (1 | subject),
              data = df_engage, family = gaussian(link = identity))
summary(model)
tab_model(model)

# Correlation analysis
resp <- identity(response)
weighted_res <- model@resp$wtres
subjects <- unique(df_engage$subject)

test <- c()
for (subject in subjects){
  id <- df_engage$subject == subject
  test[subject] <- cor(resp[id], weighted_res[id], method = c("pearson"))
}
# test
mean(na.omit(test))
```


