---
title: "eeg_eye_statistical_analysis_with_categorical_data"
---
```{r Initialization}

# Clear all
rm(list=ls())

library(yaml)
library(ggplot2)
library(feather)
library(lme4)
library(simr)
library(here)
library(sjPlot)
library(writexl)
library(ggpubr)
library(sjmisc)

# Read the configuration file
config <- yaml.load_file("../../config.yml")

eeg_eye_r_dataset_path <- here(config$eeg_eye_r_dataset_path)
df <- read.csv(eeg_eye_r_dataset_path)
df <- na.omit(df)
```


```{r Analysis of target and engage option}
# Select only static red team
df_pre_option <- subset(df, df$option_type=='pre_option')
df_static <- subset(df_pre_option, df_pre_option$complexity_type=='S002')

# Select reference level and comparison level
comparions_option <- 'engage_option'
reference_option <- 'caution_option'
df_static <-  subset(df_static, df_static$option==reference_option| df_static$option == comparions_option)

# Convert the character to numeric 
df_static['response'] <- df_static$cog_state
df_static$response[df_static$option==reference_option] <- 0
df_static$response[df_static$option==comparions_option] <- 1

# Fit the mixed effect model
model <- lmer(response ~ prob_high_eng + prob_ave_workload + pupil_size + n_fixations + fz_pz_alpha  + fz_o1_gamma + (1 |vs),data = df_static)
summary(model)
tab_model(model)
```

```{r Save the data for python processing (predictions)}
# Select only static red team
df_pre_option <- subset(df, df$option_type=='pre_option')
df_static <- subset(df_pre_option, df_pre_option$complexity_type=='S002')

# Select reference level and comparison level

comparions_option <- 'target_option'
reference_option <- 'caution_option'
df_static <-  subset(df_static, df_static$option==reference_option| df_static$option == comparions_option)
# Convert the character to numeric 
df_static['response'] <- df_static$cog_state

df_static$response[df_static$option==reference_option] <- 0
df_static$response[df_static$option==comparions_option] <- 1

# Fit the mixed effect model
model <- lmer(response ~ prob_high_eng + fz_o1_gamma + (1 | mot),data = df_static)
summary(model)
tab_model(model)


predicted <- predict(model)
true_values <- model@resp$y
predicted_values <- true_values - model@resp$wtres
df_static$predicted_values <- predicted_values
df_static$residuals <- model@resp$wtres

# Write to csv
write.csv(df_static,"df_mot_target.csv", row.names = FALSE)
```

```{r Save the data for python processing (predictions)}
# Select only static red team
df_pre_option <- subset(df, df$option_type=='pre_option')
df_static <- subset(df_pre_option, df_pre_option$complexity_type=='S002')

# Select reference level and comparison level

comparions_option <- 'engage_option'
reference_option <- 'caution_option'
df_static <-  subset(df_static, df_static$option==reference_option| df_static$option == comparions_option)
# Convert the character to numeric 
df_static['response'] <- df_static$cog_state

df_static$response[df_static$option==reference_option] <- 0
df_static$response[df_static$option==comparions_option] <- 1

# Fit the mixed effect model
model <- lmer(response ~ fz_o1_gamma + (1 |mot),data = df_static)
summary(model)
tab_model(model)


predicted <- predict(model)
true_values <- model@resp$y
predicted_values <- true_values - model@resp$wtres
df_static$predicted_values <- predicted_values
df_static$residuals <- model@resp$wtres

# Write to csv
write.csv(df_static,"df_mot_engage.csv", row.names = FALSE)
```

