# Global parameters
epoch_length: 1.0
n_electrodes: 30
freq_bands: [[4, 7], [8, 13], [14, 35], [35, 45]]
sfreq: 256.0
overlap: 0.75
subjects: [
    '2000',
    '2001',
    '2002',
    '2003',
    '2004',
    '2005',
    '2007',
    '2008',
    '2009',
  ] # 2006
sessions: ['S001', 'S002', 'S003', 'S004', 'S005']
individual_diff: ['VS', 'MOT']
##---------------------------------------------------------------------##
# Experiment 0
# Path
raw_xdf_path: 'data/raw/'
force_data_path: 'data/raw/force_data/'

raw_offset_dataset: 'data/interim/raw_offset_exp_0_dataset.h5'
raw_eeg_dataset: 'data/interim/raw_eeg_exp_0_dataset.h5'
raw_eye_dataset: 'data/interim/raw_eye_exp_0_dataset.h5'
clean_eeg_dataset: 'data/processed/clean_eeg_exp_0_dataset.h5'

eeg_features_path: 'data/processed/eeg_features_exp_0_dataframe.h5'
eye_features_path: 'data/processed/eye_features_exp_0_dataframe.h5'
individual_diff_path: 'data/processed/individual_diff_exp_0_dataframe.h5'

image_save_path: 'data/processed/image_data/'
