# Global parameters
n_nodes: 53
n_electrodes: 30
sfreq: 256.0
overlap: 0.75
subjects: [
    '2001',
    '2002',
    '2003',
    '2004',
    '2005',
    '2007',
    '2008',
    '2009',
    '2011',
    '2012',
    '2013',
    '2014',
    '2015',
    '2017',
  ] # 2006, 2000, 2016, 2019, 2010
# '2018',
# '2020',
sessions: ['S001', 'S002', 'S003', 'S004', 'S005']
individual_diff: ['VS', 'MOT']
##---------------------------------------------------------------------##
# Initial cleaning for B-Alert
# Data path
raw_xdf_path: 'data/raw/'
map_data_path: 'data/processed/map_data/'

##---------------------------------------------------------------------##
# Experiment 0
# In the experiment the data is epoched at fixed length (1 second)
epoch_length: 1.0
freq_bands: [[4, 7], [8, 13], [14, 35], [35, 45]]

# Raw data path
raw_offset_dataset: 'data/processed/offset_features_exp_0_dataset.h5'
raw_eeg_dataset: 'data/interim/raw_eeg_exp_0_dataset.h5'
raw_eye_dataset: 'data/interim/raw_eye_exp_0_dataset.h5'

# Cleaned and features data path
clean_eeg_dataset: 'data/processed/clean_eeg_exp_0_dataset.h5'
eeg_features_path: 'data/processed/eeg_features_exp_0_dataframe.h5'
eye_features_path: 'data/processed/eye_features_exp_0_dataframe.h5'
game_features_path: 'data/processed/game_features_exp_0_dataframe.h5'
offset_features_path: 'data/processed/offset_features_exp_0_dataset.h5'
individual_diff_path: 'data/processed/individual_diff_exp_0_dataframe.h5'
image_save_path: 'data/processed/image_data/'
##---------------------------------------------------------------------##
